name: Jinja CI

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  PYTHONUNBUFFERED: 1
  USER_NAME: $(echo '${{github.event.repository.full_name}}' | cut -d '/' -f 1)

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./files/requirements.txt
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Tailwind CSS
        run: |
          npm init -y --prefix ./files/static/vendor/bootstrap/
          npm install tailwindcss@latest --prefix ./files/static/vendor/bootstrap/
          npx tailwindcss init --full --prefix ./files/static/vendor/bootstrap/
          npx tailwindcss build --config ./files/static/vendor/bootstrap/tailwind.config.js --output ./files/static/vendor/bootstrap/tailwind.css
      - name: Display the content of files/static/vendor/bootstrap
        run: |
          ls -R ./files/static/vendor/bootstrap/
      - name: Update the root path
        run: |
          echo "repository info ${{ env.USER_NAME }}"
          sed -i 's/{% set home="\/" %}/{% set home="https:\/\/${{ env.USER_NAME }}.github.io\/${{ github.event.repository.name }}\/" %}/' ./files/templates/index.jinja
          echo "contents of ./files/templates/index.jinja:\n $(cat ./files/templates/index.jinja)"
      - name: Copy static files to output directory
        run: |
          mkdir -p ./output
          cp -r ./files/static ./output
      - name: Copy favicon to the source of the folder
        run: |
          cp ./favicon.ico ./output
      - name: Build Jinja Site
        run: |
          # Replace the command with your build script or static site generator
          python ./files/build.py  # Assuming you have a custom build script
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Branch to deploy the static files
          publish_dir: ./output  # Directory containing the generated static files
